#database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmall_springboot?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 驼峰命名
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
    encoding: utf-8
    content-type: text/html
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

server:
  context-path: /tmall_springboot